# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1Q9a960oNViiF3n5zj5LcKrRoJaMqFJzk?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

In [1]:
import numpy as np

In [11]:
# Задание 2
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Сложение матриц:\n{a+b}')
print(f'Перемножение матриц:\n {a@b}')

Сложение матриц:
[[ 5 -3]
 [ 3  5]]
Перемножение матриц:
 [[  4 -11]
 [ 12  -3]]


In [14]:
# Задание 3
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

def matrix_compute(a,b,c):
  return 3*a - 2*b + 4*c

print(matrix_compute(a,b,c))

[[ 11  -5]
 [  9 -12]]


In [19]:
# Задание 4
a = np.array([
              [4,1],
              [5,-2],
              [2,3]
              ])

print(f'a.T * a:\n{a.T@a}')
print(f'\na * a.T:\n{a@a.T}')

a.T * a:
[[45  0]
 [ 0 14]]

a * a.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [54]:
# Задание 5
# Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

def matrix_multiply(a,b):
  if len(a) != len(b[0]):
    print('Такие матрицы нельзя перемножить')

  # Сразу задаем размерность матрицы
  result_matrix = [[0 for k in range(len(a))] for l in range(len(a))]
  for i in range(len(a)):
    for j in range(len(b[0])):
      cell = 0
      for k in range(len(a[0])):
        cell += a[j][k]*b[k][i]
      result_matrix[j][i] = cell

  return result_matrix

In [57]:
# Проверка функции

a = np.array([[1, 9], [2, 1], [10,5]])
b = np.array([[2, 5, 12], [44, 2, 2]])

print(f'Умножение с помощью numpy:\n {a@b}')
print(f'Умножение с помощью моего алгоритма:\n {np.array(matrix_multiply(a,b))}')

Умножение с помощью numpy:
 [[398  23  30]
 [ 48  12  26]
 [240  60 130]]
Умножение с помощью моего алгоритма:
 [[398  23  30]
 [ 48  12  26]
 [240  60 130]]


In [29]:
# Задание 6

# a
x = 1
a = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Определитель матрицы\nsinx -cosx\ncosx sinx:\n{np.linalg.det(a)}')

#b
b = np.array([
              [8,4,6],
              [0,5,1],
              [0,0,9]
])
print(f'\nОпределитель матрицы:\n{int(np.linalg.det(b))}')

c = np.array([
              [2,3,4],
              [5,6,7],
              [8,9,10]
])

print(f'\nОпределитель матрицы:\n{int(np.linalg.det(c))}')

Определитель матрицы
sinx -cosx
cosx sinx:
1.0

Определитель матрицы:
360

Определитель матрицы:
0


In [33]:
# Задание 7
detA = 4
# По свойствам определителей
print(f'DetA^2 = {detA**2}')
print(f'DetA = DetA.T = {detA}')
print(f'Det(2A) = {detA*2}')

DetA^2 = 16
DetA = DetA.T = 4
Det(2A) = 8


In [34]:
# Задание 8
a = np.array([
              [-2,7,-3],
              [4,-14,6],
              [-3,7,13]            
])

if np.linalg.det(a) == 0:
  print('Матрица вырожденная')
else:
  print('Матрица невырожденная')

Матрица вырожденная


In [58]:
# Задание 9
a = np.array([
              [1,2,3],
              [1,1,1],
              [2,3,4]
])

print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

b = np.array([
              [0,0,2,1],
              [0,0,2,2],
              [0,0,4,3],
              [2,3,5,6]
])
print(f'Ранг матрицы: {np.linalg.matrix_rank(b)}')

Ранг матрицы: 2
Ранг матрицы: 3
